language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - 12
  - 14
  - 15

script:
  - npm run eslint
  - npm run test-cover

after_script:
  - npm run test-cover-report
