language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "10.15.0"
  - "11.6.0"

script:
  - npm run eslint
  - npm run test-cover

after_script:
  - npm run test-cover-report
